name: Deploy naar Mijndomein via SSH/SFTP
on:
  push:
    branches: [main]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
      - name: Bestanden syncen via SSH/rsync
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 213.249.67.33
          remote-user: f_000c0d2f
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /v3lhomewizard.3lcomputers.nl/
          rsync-options: --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore --exclude=poller/ --exclude=.github/
