name: Deploy naar Mijndomein via SFTP
on:
  push:
    branches: [main]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v4
      - name: Bestanden uploaden via SFTP
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: 213.249.67.33
          username: f_000c0d2f
          key: ${{ secrets.SSH_KEY }}
          port: 22
          uploads: |
            ./ => ./v3lhomewizard.3lcomputers.nl/
          ignore: |
            .git*
            .git*/**
            .github/**
            poller/**
            README.md
